### PR TITLE
Add plugin contents

### PR DESCRIPTION
**Pull request by igordavydsson**
Refs RND-39

### CODE REVIEW

**Comment by igordavydsson** [comment]
I had to delete the previous PR, as my fork became a standalone repo after Jesse had made this repo public.

**Comment by igordavydsson** [comment]
@suutari-ai should I still add license info for Font-Awesome and Select2, if I don't have their files in the repo now?

**Comment by suutari-ai** [comment]
Just make sure that the license info is included too when the wheel is built, i.e. that it is fetched with the rest of the stuff and that MANIFEST.in is configured to include the license files to the wheel.

**Comment by igordavydsson** [comment]
@suutari-ai yes, license gets included now too. I have tested it.

**Pull request merged**
